# -*- coding: utf-8 -*-
"""CV(Image Segmentation).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OvhcAnsx7_X-FQH3tYY3pd7PqRPo-ibe
"""

# Cell 1: Install dependencies
!pip install ultralytics transformers sentence-transformers opencv-python scikit-learn tqdm pycocoevalcap nltk -q

# Cell 2: Download COCO val2017 dataset
!wget -q http://images.cocodataset.org/zips/val2017.zip
!wget -q http://images.cocodataset.org/annotations/annotations_trainval2017.zip
!unzip -q -o val2017.zip
!unzip -q -o annotations_trainval2017.zip
print("✅ Dataset ready")

# Cell 3: Imports
import os
import json
import time
import numpy as np
from tqdm import tqdm
from PIL import Image

import torch
from ultralytics import YOLO
from transformers import BlipProcessor, BlipForConditionalGeneration
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {DEVICE}")

# Cell 4: Load COCO annotations
ANN_FILE = "annotations/captions_val2017.json"
INST_FILE = "annotations/instances_val2017.json"

with open(ANN_FILE) as f:
    cap_data = json.load(f)

with open(INST_FILE) as f:
    inst_data = json.load(f)

# Build lookups
image_id_to_name = {img["id"]: img["file_name"] for img in cap_data["images"]}

image_to_captions = {}
for ann in cap_data["annotations"]:
    fname = image_id_to_name[ann["image_id"]]
    image_to_captions.setdefault(fname, []).append(ann["caption"])

cat_id_to_name = {c["id"]: c["name"] for c in inst_data["categories"]}
image_to_objects = {}
_img_id_objs = {}
for ann in inst_data["annotations"]:
    _img_id_objs.setdefault(ann["image_id"], set()).add(cat_id_to_name[ann["category_id"]])
for img in inst_data["images"]:
    if img["id"] in _img_id_objs:
        image_to_objects[img["file_name"]] = list(_img_id_objs[img["id"]])

object_vocab = set()
for objs in image_to_objects.values():
    object_vocab |= set(objs)

print(f"✅ {len(image_to_captions)} images, {sum(len(v) for v in image_to_captions.values())} captions")

# Cell 5: Load models
print("Loading YOLOv8n...")
yolo = YOLO("yolov8n.pt")

print("Loading BLIP (Salesforce/blip-image-captioning-base)...")
blip_processor = BlipProcessor.from_pretrained("Salesforce/blip-image-captioning-base")
blip_model = BlipForConditionalGeneration.from_pretrained(
    "Salesforce/blip-image-captioning-base"
).to(DEVICE)
blip_model.eval()

print("Loading SentenceTransformer for semantic re-ranking...")
sem_model = SentenceTransformer("all-MiniLM-L6-v2")

# Pre-encode all COCO captions for semantic comparison
print("Encoding COCO caption archive (this takes ~30s)...")
all_captions = [cap for caps in image_to_captions.values() for cap in caps]
archive_embeddings = sem_model.encode(all_captions, batch_size=256,
                                       convert_to_numpy=True, show_progress_bar=True)

print("✅ All models loaded")

# Drop-in replacement for Cell 6 — fixes both issues

def generate_blip_captions(img_path, n=5):
    """Generate n diverse captions using BLIP, one at a time to avoid tensor size mismatches."""
    image = Image.open(img_path).convert("RGB")
    inputs = blip_processor(images=image, return_tensors="pt").to(DEVICE)

    captions = []

    with torch.no_grad():
        # 1 beam-search caption (highest quality)
        ids = blip_model.generate(
            **inputs,
            max_new_tokens=60,
            min_length=10,          # force at least some content
            num_beams=5,
            length_penalty=1.5,     # reward longer outputs
            repetition_penalty=1.3,
        )
        captions.append(blip_processor.decode(ids[0], skip_special_tokens=True))

        # n-1 sampling captions for diversity — generated ONE AT A TIME
        for _ in range(n - 1):
            ids = blip_model.generate(
                **inputs,
                max_new_tokens=60,
                min_length=10,
                do_sample=True,
                top_p=0.9,
                temperature=0.85,
                length_penalty=1.2,
                repetition_penalty=1.3,
            )
            captions.append(blip_processor.decode(ids[0], skip_special_tokens=True))

    return list(set(captions))  # deduplicate


# Re-run the rest of Cell 6 unchanged
def select_best_caption(candidates):
    if len(candidates) == 1:
        return candidates[0]
    emb = sem_model.encode(candidates, convert_to_numpy=True)
    scores = cosine_similarity(emb, archive_embeddings).mean(axis=1)
    return candidates[int(np.argmax(scores))]

def caption_image(img_path):
    candidates = generate_blip_captions(img_path)
    return select_best_caption(candidates)

def caption_objects(caption):
    caption_lower = caption.lower()
    return {obj for obj in object_vocab if obj in caption_lower}

print("✅ Fixed functions ready — re-run Cell 8")

# Cell 7: Quick single-image test
import matplotlib.pyplot as plt
import matplotlib.patches as patches

def caption_and_display(img_path):
    """Caption a single image and show results with YOLO detections."""
    t0 = time.time()

    # BLIP caption
    caption = caption_image(img_path)

    # YOLO detections
    result = yolo(img_path, verbose=False)[0]
    yolo_objects = list(set([yolo.names[int(c)] for c in result.boxes.cls]))

    elapsed = time.time() - t0

    # Plot
    fig, axes = plt.subplots(1, 2, figsize=(14, 5))

    # Original + YOLO boxes
    annotated = result.plot()
    axes[0].imshow(annotated[:, :, ::-1])
    axes[0].set_title(f"YOLO detections: {', '.join(yolo_objects)}", fontsize=10)
    axes[0].axis("off")

    # Caption display
    img = Image.open(img_path)
    axes[1].imshow(img)
    axes[1].set_title(f"BLIP Caption:\n\"{caption}\"", fontsize=11, wrap=True)
    axes[1].axis("off")

    plt.suptitle(f"⏱ {elapsed:.2f}s", fontsize=9)
    plt.tight_layout()
    plt.show()
    print(f"Caption: {caption}")
    print(f"YOLO objects: {yolo_objects}")
    return caption

# Test on first val image
test_img = "val2017/" + list(image_to_captions.keys())[0]
caption_and_display(test_img)

# Cell 8: Precision / Recall / F1 evaluation (50 images)
TP = FP = FN = 0
times = []

image_list = list(image_to_objects.keys())[:50]
print("Starting P/R/F1 evaluation on 50 images...\n")

for i, img_name in enumerate(image_list):
    try:
        img_path = os.path.join("val2017", img_name)
        print(f"[{i+1}/50] {img_name}")

        t0 = time.time()
        cap = caption_image(img_path)
        times.append(time.time() - t0)

        print(f"  Caption: {cap}")

        gt = set(image_to_objects[img_name])
        pred = caption_objects(cap)

        TP += len(pred & gt)
        FP += len(pred - gt)
        FN += len(gt - pred)

    except Exception as e:
        print(f"  Error: {e}")

precision = TP / (TP + FP + 1e-9)
recall = TP / (TP + FN + 1e-9)
f1        = 2 * precision * recall / (precision + recall + 1e-9)
hallucination_rate = FP / (TP + FP + 1e-9)
grounding_acc      = TP / (TP + FN + 1e-9)

print("\n===== FINAL RESULTS (50 images) =====")
print(f"Precision:          {precision:.4f}")
print(f"F1:                 {f1:.4f}")
print(f"Hallucination Rate: {hallucination_rate:.4f}")
print(f"Grounding Accuracy: {grounding_acc:.4f}")
print(f"Avg Time/image:     {np.mean(times):.2f}s")

# Cell 9: BLEU + METEOR evaluation (100 images)
import nltk
nltk.download('wordnet', quiet=True)
nltk.download('omw-1.4', quiet=True)

from pycocoevalcap.bleu.bleu import Bleu
from pycocoevalcap.meteor.meteor import Meteor
from pycocoevalcap.rouge.rouge import Rouge

gts = {}
res = {}

image_list_100 = list(image_to_captions.keys())[:100]
print("Running BLEU/METEOR/ROUGE evaluation on 100 images...")

for img_name in tqdm(image_list_100):
    try:
        img_path = os.path.join("val2017", img_name)
        pred_caption = caption_image(img_path)
        gts[img_name] = image_to_captions[img_name]
        res[img_name] = [pred_caption]
    except Exception as e:
        print(f"Error on {img_name}: {e}")

# BLEU
bleu_scorer = Bleu(4)
bleu_scores, _ = bleu_scorer.compute_score(gts, res)
print(f"\nBLEU-1: {bleu_scores[0]:.4f}")
print(f"BLEU-2: {bleu_scores[1]:.4f}")
print(f"BLEU-3: {bleu_scores[2]:.4f}")
print(f"BLEU-4: {bleu_scores[3]:.4f}")

# METEOR
try:
    meteor = Meteor()
    meteor_score, _ = meteor.compute_score(gts, res)
    print(f"METEOR: {meteor_score:.4f}")
except Exception as e:
    print(f"METEOR skipped: {e}")

# ROUGE-L
try:
    rouge = Rouge()
    rouge_score, _ = rouge.compute_score(gts, res)
    print(f"ROUGE-L: {rouge_score:.4f}")
except Exception as e:
    print(f"ROUGE-L skipped: {e}")

